# Generated by Django 6.0.3 on 2026-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order'], 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='customization',
            options={'verbose_name_plural': 'Customizations'},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order'], 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order'], 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name_plural': 'Personal Info'},
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.AddField(
            model_name='certification',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customization',
            name='color_accent',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='customization',
            name='color_background',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='customization',
            name='color_primary',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AlterField(
            model_name='customization',
            name='color_secondary',
            field=models.CharField(default='#1e40af', max_length=7),
        ),
        migrations.AlterField(
            model_name='customization',
            name='color_text',
            field=models.CharField(default='#1f2937', max_length=7),
        ),
        migrations.AlterField(
            model_name='customization',
            name='font_body',
            field=models.CharField(default='Source Sans Pro', max_length=100),
        ),
        migrations.AlterField(
            model_name='customization',
            name='font_heading',
            field=models.CharField(default='Playfair Display', max_length=100),
        ),
        migrations.AlterField(
            model_name='customization',
            name='font_size_body',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='customization',
            name='font_size_heading',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='customization',
            name='font_style',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='customization',
            name='photo_shape',
            field=models.CharField(default='circle', max_length=20),
        ),
        migrations.AlterField(
            model_name='customization',
            name='spacing_element_gap',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='customization',
            name='spacing_section_gap',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='customization',
            name='template_id',
            field=models.CharField(default='modern', max_length=20),
        ),
        migrations.AlterField(
            model_name='customization',
            name='text_direction',
            field=models.CharField(default='ltr', max_length=3),
        ),
        migrations.AlterField(
            model_name='cv',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='template_id',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('creative', 'Creative'), ('professional', 'Professional'), ('executive', 'Executive'), ('tech', 'Tech'), ('academic', 'Academic')], default='modern', max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(default='Untitled CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qrconfig',
            name='size',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='qrconfig',
            name='style',
            field=models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded')], default='square', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrconfig',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='Technical', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
